### PR TITLE
Mvp flow

### PR DESCRIPTION
**Pull request by manangouhari**
**What does this PR do?**
Implements the main user flow ->
landing page -> Academy -> Module -> Claim bot

### CODE REVIEW

**Comment by manangouhari** [comment]
@bhaskarSingh please try out the flow.

**Comment by bhaskarSingh** [comment]
I'll check when it's finished. Right now, missing popup modal before directing to customizer view & logic to make sure the user can only mint one nft per module.

**Comment by manangouhari** [comment]
> I'll check when it's finished. Right now, missing popup modal before directing to customizer view & logic to make sure the user can only mint one nft per module.

Are we allowing the user to mint multiple NFTs? One per module?

**Comment by bhaskarSingh** [comment]
Yes.

**Comment by bhaskarSingh** [comment]
In total, one xtzAddress can mint 5 bots, one per module.

**Comment by bhaskarSingh** [comment]
>  logic to make sure the user can only mint one nft per module.
@manangouhari you can leave it. I'll take lead here, I'll have to update the smart contract code to make this work properly.

Can you add logic so that customizer only shows up if 100% progress is completed for every module after module 1?

> missing popup modal before directing to customizer view
(https://www.figma.com/proto/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=1039%3A32&viewport=241%2C488%2C0.015625&scaling=min-zoom) rather than showing pop-up modal in customizer view. Make it pop-up on clicking the last chapter of every modal & then direct the user from there to the customizer view this way you will not have to re-config the auth logic.

**Comment by bhaskarSingh** [comment]
TODO list before merging this PR

- [ ] Add pop-modal (https://www.figma.com/proto/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=1039%3A32&viewport=241%2C488%2C0.015625&scaling=min-zoom) before very module last chapter before redirecting to bot customizer view.
- [ ] Make cryptoverse wars logo clickabke with link re-directing to `/tezos`(homepage)
- [ ] Fix navbar academy link. it should go to `tezos/academy` rather than `/overview`

**Comment by bhaskarSingh** [comment]
Shiting conversion here

> When somebody goes to customizebot, they're forced to connect their wallet, with no option to skip
Shouldn't claiming a bot be an optional thing?

Yes, it's a valid point. For that simply add another button redirecting to the academy when showing the  [pop-modal](https://www.figma.com/proto/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=1039%3A32&viewport=241%2C488%2C0.015625&scaling=min-zoom) before very module last chapter before redirecting to bot customizer view.

**Comment by bhaskarSingh** [comment]
@manangouhari  Looking into why auth is failing.

**Comment by bhaskarSingh** [comment]
@manangouhari  It's working locally but when I click on claim bot it redirects to the claim-bot url again, why is that?

**Comment by manangouhari** [comment]
@bhaskarSingh please review and let me know if something's left on this PR

**Comment by manangouhari** [comment]
why did you mark it as blocked @bhaskarSingh

**Comment by bhaskarSingh** [comment]
> why did you mark it as blocked @bhaskarSingh

Due to authentication issue. I have created another PR with the required fixes.

**Comment by manangouhari** [comment]
Okay.

**Pull request closed without merging**
