### PR TITLE
Academy

### PR DESCRIPTION
**Pull request by manangouhari**
**What does this PR do?**
Updated the backend API url.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
@manangouhari close this PR. Create a new branch from the develop branch whenever working on something new after pull in the latest changes. This should resolve the issue of unnecessary commits showing up.

**Comment by manangouhari** [comment]
> @manangouhari close this PR. Create a new branch with a new name which isn't already created from the develop branch whenever working on something new after pulling in the latest changes. This should resolve the issue of unnecessary commits showing up.
> 
> Since this branch is already merged.


Sorry, slipped up on it this time. Is it okay if I merge this one and take care from next time?

**Comment by bhaskarSingh** [comment]
I wouldn't do that, it will create unnecessary bugs later.

**Comment by prastut** [comment]
Agree with @bhaskarSingh, the develop branch history will get fucked and 5 mins saved here will be a massive pain in the future. (talking out of experiencing the latter)

**Comment by manangouhari** [comment]
👍 closing this PR

**Comment by bhaskarSingh** [comment]
@manangouhari  I think this same issue is with the backend repo last merge. Please revert it & fix it also.

**Pull request closed without merging**
