### PR TITLE
Copy fixes

### PR DESCRIPTION
**Pull request by manangouhari**
**Tries** to resolve issues issues mentioned by @prastut - #265, #277

### CODE REVIEW

**Comment by manangouhari** [comment]
@harsh242 look at the design of second section on the landing page.

**Comment by harsh242** [comment]
- [Loom Video](https://www.loom.com/share/a3bda7b4004c4219b6e1e3a89bae1fca)
- [Design](https://www.figma.com/file/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=2010%3A4)

Did you change the copy from `create your own currency` to `create your currency` ?

**Comment by prastut** [comment]
@manangouhari 

Recommended fixes: 

Need some spacing between lines here: 
image

Rest everything looks so good 🥺

**Review by prastut — APPROVED** [review]

**Comment by manangouhari** [comment]
Closes #265 #277

**Pull request merged**
