### PR TITLE
Basic stylesheet

### PR DESCRIPTION
**Pull request by manangouhari**
**What does this PR do?**
Set up the design system.
Added a `src/styles` folder with colours, spacing, and typography.

### CODE REVIEW

**Comment by manangouhari** [comment]
@bhaskarSingh requesting you to take a look. Build is failing because it one of the Mdx file comes back as null. Beats me, we haven't touched any of that.

**Comment by bhaskarSingh** [comment]
> @bhaskarSingh requesting you to take a look. Build is failing because it one of the Mdx file comes back as null. Beats me, we haven't touched any of that.

It's working now. Which one do I review b/w to pull the request?

**Comment by manangouhari** [comment]
Review this one. 
The flow we've decided is -
We'll checkout out of v2 branch and merge back features into v2 branch. 
v2 will finally be merged into develop.

**Comment by bhaskarSingh** [comment]
> The flow we've decided is -
We'll checkout out of v2 branch and merge back features into v2 branch.
v2 will finally be merged into develop.

Why v2 and not merge directly into develop ?

**Comment by manangouhari** [comment]
Isn't develop setup to auto-deploy to https://develop.cryptocodeschool.in?
If it is(which I assumed), didn't want half-baked things being live on that domain.

**Comment by bhaskarSingh** [comment]
> Isn't develop setup to auto-deploy to https://develop.cryptocodeschool.in?
Yes.
> If it is(which I assumed), didn't want half-baked things being live on that domain.
Develop branch is for testing purposes only. No need to create a v2 branch. It will only complicate it further.

The **master** branch is where live production changes are deployed.

**Comment by bhaskarSingh** [comment]
> Set up the design system.

Why do we need to create a design system manually. Can't we use a library for it, for example, tailwind CSS must have its own design system which would be much more robust.

**Comment by manangouhari** [comment]
> > Set up the design system.
> 
> Why do we need to create a design system manually. Can't we use a library for it, for example, tailwind CSS must have its own design system which would be much more robust.

Tailwindcss's design system is only good for its own classes. Our requirements will surpass what Tailwind can do and would call for a lot of custom CSS. Hence, decided to go with styled components, and created the base design system so that we can just import the vars and use. This is the same design system that the design team had on Figma.

**Comment by manangouhari** [comment]
> > Isn't develop setup to auto-deploy to https://develop.cryptocodeschool.in?
> 
> Yes.
> 
> > If it is(which I assumed), didn't want half-baked things being live on that domain.
> 
> Develop branch is for testing purposes only. No need to create a v2 branch. It will only complicate it further.
> 
> The **master** branch is where live production changes are deployed.

Got it.

**Comment by bhaskarSingh** [comment]
> Tailwindcss's design system is only good for its own classes. Our requirements will surpass what Tailwind can do and would call for a lot of custom CSS. Hence, decided to go with styled components, and created the base design system so that we can just import the vars and use. This is the same design system that the design team had on Figma.

Got it. Can't we use tailwind CSS(or any other CSS lib) as the base & then use custom CSS on top of it. Is there any caveat or drawback to it?

**Comment by manangouhari** [comment]
> > Tailwindcss's design system is only good for its own classes. Our requirements will surpass what Tailwind can do and would call for a lot of custom CSS. Hence, decided to go with styled components, and created the base design system so that we can just import the vars and use. This is the same design system that the design team had on Figma.
> 
> Got it. Can't we use tailwind CSS(or any other CSS lib) as the base & then use custom CSS on top of it. Is there any caveat or drawback to it?

Drawback is maintaining CSS at multiple places. Like half our styles would be there on the component as classes, half of em as styled components.

**Review by bhaskarSingh — APPROVED** [review]

**Comment by bhaskarSingh** [comment]
> Drawback is maintaining CSS at multiple places.

Have you checked this: https://www.freecodecamp.org/news/how-to-style-your-react-apps-with-less-code-using-tailwind-css-and-styled-components/

This can tackle the above-mentioned issue.

Using tailwind CSS + styled-components on top of it will help us build quicker. Writing CSS manually has it's own downside of maintenance, I have been there.

**Comment by manangouhari** [comment]
> > Drawback is maintaining CSS at multiple places.
> 
> Have you checked this: https://www.freecodecamp.org/news/how-to-style-your-react-apps-with-less-code-using-tailwind-css-and-styled-components/
> 
> This can tackle the above-mentioned issue.
> 
> Using tailwind CSS + styled-components on top of it will help us build quicker. Writing CSS manually has it's own downside of maintenance, I have been there.

This seems nice. Can you try setting it up?
Meanwhile, I'll look into the database connection on the backend.

**Pull request merged**
