### PR TITLE
fixes #233

### LINKED ISSUE #233: Markdown rendering issues
**Description of the bug**
Markdown renderer is not completely accurate.
1. Code blocks and code snippets are not in dark mode.
2. Tables are not coloured.
3. List items that start with code are broken.

image

image

### PR DESCRIPTION
**Pull request by bhaskarSingh**
**What does this PR do?**
closes #233

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
@manangouhari Please check if everything is rendering as intended or not.

**Comment by manangouhari** [comment]
> @manangouhari Please check if everything is rendering as intended or not.

The table and code are still light mode. 
Code blocks are working properly tho.

**Comment by bhaskarSingh** [comment]
> The table and code are still light mode.
Code blocks are working properly tho.

It's fixed now.

**Comment by manangouhari** [comment]
> > The table and code are still light mode.
> Code blocks are working properly tho.
> 
> It's fixed now.

Perfect 😍
The interface looks soooo beautiful now

**Pull request merged**
