### PR TITLE
Fix: customizer lighting setup

### PR DESCRIPTION
**Pull request by harsh242**
**What does this PR do?**
Fix lighting being wonky sometimes issue mentioned here #231

**How should this be manually tested?**
`/tezos/customizebot`

### CODE REVIEW

**Review by bhaskarSingh — APPROVED** [review]

**Comment by bhaskarSingh** [comment]
@aayushsaini1 What's your take on the lighting setup? https://deploy-preview-293--blissful-mcnulty-82f253.netlify.app/tezos/customizebot

**Comment by aayushsaini1** [comment]
>What's your take on the lighting setup?
Overall lighting Looks good, but the spots/reflection are a bit too harsh.

**Comment by harsh242** [comment]
https://threejs.org/editor/
@aayushsaini1 please try a lighting setup here.

**Comment by aayushsaini1** [comment]
@harsh242 Here's the setup

[sceneV1.zip](https://github.com/buidl-labs/crypto-code-school-inside-tezos/files/6169717/sceneV1.zip)

**Comment by harsh242** [comment]
> @harsh242 Here's the setup
> There was an option to adjust tone mapping and shadows rendering and I think this is as close I could get to how it looks like in Blender.
> 
> [sceneV1.zip](https://github.com/buidl-labs/crypto-code-school-inside-tezos/files/6169717/sceneV1.zip)

These were a little more bright, have reduced intensities a little.
In this model it looks bright too, but in the new one it looks good.

**Comment by harsh242** [comment]
@aayushsaini1 @bhaskarSingh please check the lighting have reduced the intensities a little.

**Comment by harsh242** [comment]
Closing this as not using three js light setup

**Pull request closed without merging**
