### PR TITLE
Interface for Smartpy compiler.

### PR DESCRIPTION
**Pull request by manangouhari**
**What does this PR do?**
Integrates an interface for the smartpy compiler

**Description of Task to be completed?**
- Interface to show compiled Michelson and Storage

**How should this be manually tested?**
Go through the chapters of module-2 and module-3. Look at the compiled code by clicking on "Show Compiled Code" that is present when you click "Check"

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
@manangouhari  Looks good! Fill the template and I will merge it then.

**Comment by manangouhari** [comment]
> @manangouhari Looks good! Fill the template and I will merge it then.

Build has failed.

**Comment by bhaskarSingh** [comment]
@manangouhari  Error: can't find `dot-prop` npm package. Please do the needful.

**Comment by manangouhari** [comment]
TODO:
1. Fix edge cases where there is no contract in the code.
2. Loading indicator when running the code.
3. Debug code for inter-contract calling.

**Comment by bhaskarSingh** [comment]
Also, remove/fix the [control + z] command for undoing, it doesn't update the values.

**Comment by manangouhari** [comment]
> Also, remove/fix the [control + z] command for undoing, it doesn't update the values.

Can you please provide me more context around this?

**Pull request merged**
