### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by harsh242**
**What does this PR do?**
Fixes UI issues mentioned here: [figma](https://www.figma.com/file/eUQ3EIhaGW2N8CkTu6Ndnm/BUIDL-Labs---Tezos---Cryptoverse-Wars---Final-Designs?node-id=1724%3A6)

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
> fix:make checkbox disabled when only one is selected in marketplace

This feature is confusing d3045d7. I think the default is okay.

**Comment by harsh242** [comment]
> > fix:make checkbox disabled when only one is selected in marketplace
> 
> This feature is confusing [d3045d7](https://github.com/buidl-labs/crypto-code-school-inside-tezos/commit/d3045d72c1515a1e1ec12b492768b63b17a5b814). I think the behaviour default is okay.

When both are not selected it shows nothing😅

**Comment by bhaskarSingh** [comment]
Please update the copy for network fee to `Network fee is what you offer to pay the validators ( responsible for verifying transactions on the tezos blockchain ) in a tiny measurement of XTZ ) for each operation to execute the smart contract.`

> When both are not selected it shows nothing😅
It's okay.

**Comment by bhaskarSingh** [comment]
Reason for build error `Can't resolve 'src/images/Add.png' in '/opt/build/repo/src/pages/tezos'`.

**Comment by bhaskarSingh** [comment]
@harsh242  You can move on to creating the video after resolving the build error & issue #189.

**Review by bhaskarSingh — APPROVED** [review]

**Pull request merged**
