### PR TITLE
Feature update new curriculum

### PR DESCRIPTION
**Pull request by prastut**
### Before you submit, please check that:

- [ ] You labeled the PR with appropriate labels, if any.
- [ ] You mentioned a related issue if this PR related to it, e.g. `Fixes #22` or `Related #17`.
- [ ] You performed a self-review of your own code
- [ ] You commented on code, particularly in hard-to-understand areas
- [ ] You asked any particular reviewer to review. If you aren't sure, ask.
- [ ] Your PR adheres to our `CONTRIBUTION GUIDELINES`

After you've read this notice feel free to remove it.
✄ -----------------------------------------------------------------------------

**What does this PR do?**
A clear and concise description of what the PR aims to accomplish.

**Description of Task to be completed?**

**How should this be manually tested?**
A clear and concise description of how the changes can be tested.

**Any background context you want to provide?**

**Screenshots(optional)**
If applicable, add screenshots to help to explain the problem/solution.

**Additional context(optional)**
Add any other context if any.

### CODE REVIEW

**Comment by prastut** [comment]
@bhaskarSingh FYI when copying from HackMD `<br />` tags were bricking the code. Removing them solved the issue. Just wanted to drop this in your mindspace in case of a future bug that comes up.

**Comment by bhaskarSingh** [comment]
> FYI when copying from HackMD <br /> tags were bricking the code. 

Actually `br` element works just fine, just make sure while importing from HackMD `br` tags are closed (`<br/>`), Encountered this issue myself and that was the cause of it.

**Comment by bhaskarSingh** [comment]
We need reaction option for gifs

**Comment by prastut** [comment]
> We need reaction option for gifs

@bhaskarSingh we definitely do.

**Comment by prastut** [comment]
@bhaskarSingh I wanted your opinion on whether we should move forward with transaction-related stuff (buy/sell bullets/moves/plants) or include that in the medium chapter. 

The first lesson is already too long with 14 chapters.

**Comment by bhaskarSingh** [comment]
> The first lesson is already too long with 14 chapters.

I agree we can divide chapters into two or three modules for easier consumption

> I wanted your opinion on whether we should move forward with transaction-related stuff (buy/sell bullets/moves/plants) or include that in the medium chapter.

Yup, transaction-related concepts will be too much for beginner chapter.


Also noticed, In some places, we are using params and some cases value is being passed directly, is that on purpose?

```
    @sp.entry_point
    def change_name(self, params): 
        self.data.name = params.new_name
    
    # Define move_horizontally entry point function
    @sp.entry_point
    def move_horizontally(self, update_to):
        self.data.coordinate_x += update_to
```

**Comment by prastut** [comment]
> Also noticed, In some places, we are using params and some cases value is being passed directly, is that on purpose?

Naah, I just ran out of creative juices there. Let's stick to one. I think there are more cases of value directly being passed than params and let's shift to that.

**Pull request merged**
