### PR TITLE
New cryptobot page implemented

### PR DESCRIPTION
**Pull request by manangouhari**
**What does this PR do?**
It's a draft right now. Need to iron out bugs, and edge-cases.
But, feel free to test it out, and document the bugs.

### CODE REVIEW

**Comment by manangouhari** [comment]
@harsh242 and @bhaskarSingh please test this out, and let me know where it breaks.

**Comment by manangouhari** [comment]
@bhaskarSingh  please add this to env variables in netlify to fix the build.
`GATSBY_EXPERIMENTAL_ROUTING_APIS=1`

**Comment by bhaskarSingh** [comment]
> @bhaskarSingh please add this to env variables in netlify to fix the build.
GATSBY_EXPERIMENTAL_ROUTING_APIS=1

Done.

**Comment by manangouhari** [comment]
@bhaskarSingh it's ready to be merged now. Kindly review.

**Comment by bhaskarSingh** [comment]
Throws error when I try to load my owned bots https://www.loom.com/share/81e1f0a9e26746509b833662ae13eb73

**Comment by manangouhari** [comment]
Can you please send me the screenshot of error messages in the console.

**Comment by bhaskarSingh** [comment]
Screenshot 2021-03-01 at 10 40 22 PM

**Comment by manangouhari** [comment]
Why are there 10 tokens, but only 7 token holders @bhaskarSingh ?
image

**Comment by manangouhari** [comment]
Could there possibly be something wrong with BCD indexing APIs?

In the contract, there are 13 items in the ledger. 
But, in the ledger that we get back on the frontend, there are only 10 items.

image

image

**Comment by manangouhari** [comment]
@bhaskarSingh should be fixed now.

**Comment by manangouhari** [comment]
For some reason, the loader isn't spinning in production. Can you pleas take a look at that @bhaskarSingh ?

**Comment by bhaskarSingh** [comment]
@manangouhari You can move to the next task. I will take lead for all the edge cases for this PR.

**Comment by bhaskarSingh** [comment]
```
PageCreator: Found a client route, but the proper env was not set to enable this experimental feature. Please run again with `GATSBY_EXPERIMENTAL_ROUTING_APIS=1` to enable.
```

Throws above error while building. How do I set it up locally?

**Pull request closed without merging**
