### PR TITLE
Store Cryptobot images to IPFS, and token metadata 

### PR DESCRIPTION
**Pull request by manangouhari**
**What does this PR do?**

1. Saves bot image within token_metadata 
2. Handles loading of const json metadata
3. Abstract the `NETWORK` variable to make switching b/w test & main-net easier.

### CODE REVIEW

**Comment by manangouhari** [comment]
Getting this error on clicking `"Confirm"` on the `/tezos/claim-transaction` page. 
It's due to some Beacon error which I can't figure out. 
@bhaskarSingh please take a look.

image

**Comment by manangouhari** [comment]
WHAT!? Can't make sense of this.

It works in the deployed preview link, but not locally on my machine.

**Comment by manangouhari** [comment]
Check the contract on [BCD](https://better-call.dev/delphinet/KT19XZU3pRi6fd1dZinsXDGoKe2QdrU9ePjk/operations) - the latest minted token has an `imageURI`.

**Comment by bhaskarSingh** [comment]
> Check the contract on BCD - the latest minted token has an imageURI.

Checked, it's not loading the image. Just shows random strings.

**Comment by manangouhari** [comment]
> > Check the contract on BCD - the latest minted token has an imageURI.
> 
> Checked, it's not loading the image. Just shows random strings.



That is the base64 encoded form of the image.

https://github.com/buidl-labs/crypto-code-school-inside-tezos/issues/192#issuecomment-790549889

**Comment by bhaskarSingh** [comment]
Base64 is enough for our use-case. @manangouhari  Can you update the frontend so that only JSON metadata is stored with relevant fields.

**Comment by manangouhari** [comment]
> @manangouhari Can you update the frontend so that only JSON metadata is stored with relevant fields within token_metadata.

Didn't completely understand. Can you please explain

**Comment by bhaskarSingh** [comment]
Implementing functionailty on the frontend for gettings ipfs hash from `/api/upload-json-metadata-to-ipfs` endpoint for uploading it the contract token_metadata.

**Comment by manangouhari** [comment]
> Implementing functionailty on the frontend for gettings ipfs hash from `/api/upload-json-metadata-to-ipfs` endpoint for uploading it the contract token_metadata.


Wouldn't you need to change the smart contract to take a string/bytes instead of a map?

**Comment by bhaskarSingh** [comment]
> Wouldn't you need to change the smart contract to take a string/bytes instead of a map?

The data type is the map only, just need to change the type from string to bytes for the value.

**Comment by manangouhari** [comment]
> > Wouldn't you need to change the smart contract to take a string/bytes instead of a map?
> 
> The data type is the map only, just need to change the type from string to bytes for the value.

Yes, right now `metadata` accepts a map, but we need it to accept a string/bytes which will be the IPFS hash.
Let me know if I'm missing something.

**Comment by bhaskarSingh** [comment]
> Yes, right now metadata accepts a map, but we need it to accept a string/bytes which will be the IPFS hash.
Let me know if I'm missing something.

Hmm. Yes, will need to take care of the conversion. I will take lead here. @manangouhari can you think of what's the next critical constraint is & take the lead for it.

**Comment by manangouhari** [comment]
> > Yes, right now metadata accepts a map, but we need it to accept a string/bytes which will be the IPFS hash.
> > Let me know if I'm missing something.
> 
> Hmm. Yes, will need to take care of the conversion. I will take lead here. @manangouhari can you think of what's the next critical constraint is & take the lead for it.

I don't see any other **critical constraint**. 
What do you think we need to focus on next?

**Pull request merged**
