### PR TITLE
Reddit Launch fixes - Harsh

### PR DESCRIPTION
**Pull request by harsh242**
**What does this PR do?**
Implements #244 #236 #234 #172

### CODE REVIEW

**Comment by manangouhari** [comment]
After I sign-in from the landing page, and go through the first module. After clicking "Finish," it takes me to `/tezos/customizebot` page, and it blows up.

image

**Comment by harsh242** [comment]
@manangouhari  @bhaskarSingh @aayushsaini1 Please check if the lighting issue still happens, model will take a little bit of time to load since it is not compressed.

Drei environment loader had issues, so created a custom environment loader.

Let me know if the issue still persists.

**Comment by harsh242** [comment]
@bhaskarSingh Please review this.

**Review by bhaskarSingh — APPROVED** [review]
closes #244 #236 #234 #172

**Comment by bhaskarSingh** [comment]
closes #234 
closes #172

**Pull request merged**
