### PR TITLE
Merging v2 into develop.

### PR DESCRIPTION
**Pull request by manangouhari**
Merging v2 into develop. Will branch out from develop itself.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
> Drawback is maintaining CSS at multiple places.

Have you checked this: https://www.freecodecamp.org/news/how-to-style-your-react-apps-with-less-code-using-tailwind-css-and-styled-components/

This can tackle the above-mentioned issue.

Using tailwind CSS + styled-components on top of it will help us build quicker. Writing CSS manually has it's own downside of maintenance, I have been there.

**Comment by manangouhari** [comment]
> > Drawback is maintaining CSS at multiple places.
> 
> Have you checked this: https://www.freecodecamp.org/news/how-to-style-your-react-apps-with-less-code-using-tailwind-css-and-styled-components/
> 
> This can tackle the above-mentioned issue.
> 
> Using tailwind CSS + styled-components on top of it will help us build quicker. Writing CSS manually has it's own downside of maintenance, I have been there.
> 
> @manangouhari  What's your take on this.

Looks good to me. I myself am more than happy using Tailwind. 
Alt approach would be to just use tailwind, without styled-components. Along with custom css through css modules wherever necessary. Not able to make sense of mixing styled-comps with tailwindcss.

**Comment by bhaskarSingh** [comment]
Great, then we are using **tailwind** going forward.

> Not able to make sense of mixing styled-comps with tailwindcss.
This helps abstract core logic, which then helps in reusing the components.

@manangouhari  Remove all unnecessary files that wouldn't be needed now as we are using tailwind going forward. After which I will merge the PR into develop.

**Comment by bhaskarSingh** [comment]
Helpful link for setting up tailwind with gatsby: https://tailwindcss.com/docs/guides/gatsby

**Comment by harsh242** [comment]
@manangouhari let me know once you have cleaned up files and set up the tailwind, I'll then clone the repo and will start working on setting up the basic components.

**Comment by manangouhari** [comment]
> @manangouhari let me know once you have cleaned up files and set up the tailwind, I'll then clone the repo and will start working on setting up the basic components.

@harsh242  i'm setting up the `tailwind.config.js` now.
Are all the colors(50-900) necessary or do we need a subset of them?

**Comment by bhaskarSingh** [comment]
@harsh242 @manangouhari  Before start working on anything, please create an issue for it & assign yourself to that issue. 

Now that more than two individuals are working on the project this becomes very important for providing clarity.

**Comment by manangouhari** [comment]
> @harsh242 @manangouhari  Before start working on anything, please create an issue for it & assign yourself to that issue. 
> 
> Now that more than two individuals are working on the project this becomes very important for providing clarity.

Got it, makes sense.

**Comment by bhaskarSingh** [comment]
@manangouhari can you resolve the conflicts so that I can merge it?

**Comment by manangouhari** [comment]
I don't think we need to merge this now. We directly merged the other branch into develop.

**Comment by bhaskarSingh** [comment]
Aah! yes, yes.

**Pull request closed without merging**
