### PR TITLE
[Dependencies] - Updated brython to version 3.9.0

### PR DESCRIPTION
**Pull request by RomarQ**
- [ ] You labeled the PR with appropriate labels, if any.
- [x] You mentioned a related issue if this PR related to it, e.g. `Fixes #22` or `Related #17`.
- [x] You performed a self-review of your own code
- [ ] You commented on code, particularly in hard-to-understand areas
- [ ] You asked any particular reviewer to review. If you aren't sure, ask.
- [x] Your PR adheres to our `CONTRIBUTION GUIDELINES`

**What does this PR do?**

Fixes the following issue: https://github.com/brython-dev/brython/issues/1527

**Description of Task to be completed?**

Updated Brython dependency to version 3.9.0 which fixes the import issue.

### CODE REVIEW

**Comment by bhaskarSingh** [comment]
It does resolve the issue with importing smartpy error. Now, if I run

```javascript
window.generate(`import smartpy as sp

class Cryptobot(sp.Contract):

    def __init__(self, manager_address, life_state):
        
        self.init(
            bot_manager = manager_address,
            name = "terminator",
            is_alive = life_state,
            
            coordinate_x = sp.int(0),
            coordinate_y = sp.nat(0),
            
            plasma_bullet_count = 5,

            record_alien_kills = {
                "simple_alien": sp.nat(0),
                "boss_alien": sp.nat(0),
            }
            
        )

    @sp.entry_point
    def change_name(self, new_name):
        sp.verify(
            self.data.bot_manager == sp.sender,
            message = "Error: non manager call"
        )

        self.data.name = new_name
    
    @sp.entry_point
    def move_horizontally(self, update_to):
        sp.verify(
            self.data.bot_manager == sp.sender,
            message = "Error: non manager call"
        )
            
        self.data.coordinate_x += update_to
    
    @sp.entry_point
    def move_vertically(self, update_to):
        
        sp.verify(
            self.data.bot_manager == sp.sender,
            message = "Error: non manager call"
        )
            
        self.data.coordinate_y += update_to

        
    @sp.entry_point
    def shoot_alien(self, alien_type):
        
        sp.verify(
            self.data.bot_manager == sp.sender,
            message = "Error: non manager call"
        )

        sp.if self.data.plasma_bullet_count >= 1:
            self.data.plasma_bullet_count -= 1
            self.data.record_alien_kills[alien_type] += 1
        sp.else:
            sp.failwith("Error: you ran out of bullets! Please buy more!")

    
@sp.add_test(name = "Ending")
def test():
    scenario = sp.test_scenario()
    
    ## Class Invokation
    my_address = sp.address("tz1Syu3KacZ8cy4286a4vaCeoMtwqVKHkaoj")

    test_bot =  Cryptobot(manager_address = my_address, life_state = True)
    
    ## Testing contract
    scenario += test_bot
    
    scenario += test_bot.change_name("punky terminator").run(sender = my_address)
    
    scenario.verify(test_bot.data.is_alive == True)
    
    scenario += test_bot.move_horizontally(2).run(sender = my_address)
    
    scenario += test_bot.move_vertically(1).run(sender = my_address)
    
    scenario += test_bot.shoot_alien("simple_alien").run(sender = my_address)
    
    scenario += test_bot.shoot_alien("boss_alien").run(sender = my_address)
    
`)
```

It throws this error:

Screenshot 2020-11-03 at 6 44 07 AM

**Comment by prastut** [comment]
@bhaskarSingh this seems like a case of running a recursive loop that is so big that we exhaust the stack range. 
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError for more details. 

Now there could be two ways to debug this: 

- Either reduce the recursiveness some way. 
- If that is not possible, increase stack range. 


Documenting probable solutions that come to mind for both. 

#### Either reduce the recursiveness some way. 

Some speculations from my end: 

- Sometimes the library is loaded twice, get's called twice. 
  - See the last error on this page: http://net-informations.com/js/err/range.htm
  - My bet is that our usecase has something to do with this error. 
- Or there is a recursive loop that is being caused due to unforeseen human error. 
   - Check the call stack, it will reveal what's causing the problem. 

#### If that is not possible, increase stack range. 

- Currently, we serve cryptoverse wars through a combination of gatsby and netlify. 
  - Somebody is facing a similar issue here: https://github.com/gatsbyjs/gatsby/issues/18577
  - Though Netlify is able to build the site as seen above, so I am not sure that would be the error. 

============

Tangentially had an another idea: 
- Given that we got the compiler working on a server in an isolated manner 
- but don't want the headache of maintaining the server

We could try [Netlify functions](https://www.netlify.com/products/functions/) for just making an endpoint to get results from the compiler. 
 - It is free around 125k calls/month types. 
 - Assuming 100 calls per user throughout the entire course of phase 2, it will scale to 1,250 users. 

That works. 

If and when the platform get's scale bigger than that, then that's a good problem to solve then. 
Not now. 

"Premature optimization is the root of all evil" - Donald Knuth. I read this in the morning and realized that getting it right with Gatsby now feels like this.

**Comment by RomarQ** [comment]
> It throws this error:

Hi @bhaskarSingh that seems like a problem from converting the python object to JS. (try tweaking that logic in smartpyio.py)

**Comment by bhaskarSingh** [comment]
@RomarQ  After updating Brython to 3.9.0 & tinkering around python obj to js conversion logic. still getting the same error as above(Javascript exception: RangeError: Maximum call stack size exceeded). It seems to work perfectly fine when using the Brython 3.7.0 version.

I tested it in isolation, have attached the files below.
[smartpy-demo_example.zip](https://github.com/buidl-labs/crypto-code-school-inside-tezos/files/5480188/smartpy-demo_example.zip)

**Comment by bhaskarSingh** [comment]
It's working now! Thank you so much @RomarQ for looking into it.

**Pull request merged**
