### PR TITLE
SEO added to a few pages.

### PR DESCRIPTION
**Pull request by manangouhari**

### CODE REVIEW

**Comment by manangouhari** [comment]
@bhaskarSingh & @harsh242 requesting to review and let me know if I missed out on the SEO for some page, which is highly likely.

**Review by harsh242 — COMMENTED** [review]
- I think you forgot the Auth page.
- Also, Just a suggestion to keep Cryptobot at all the places instead of bot
             - Like in `/claim-transaction`
 - And in `/transaction` can you do it like "buy cryptobot" or something like that🤔

**Comment by manangouhari** [comment]
@bhaskarSingh it's ready for review now.

**Comment by bhaskarSingh** [comment]
@manangouhari Please add a description of what this PR intends to accomplish.

**Pull request merged**
